### ISSUE TITLE
Failed notification on fresh install / wrong line endings

### ISSUE THREAD

**Issue by mindsolve** [deexno/checkmk-telegram-plus#1]
On a fresh install of this project following the installation instructions, CheckMK cannot send notifications with the following error message:
`[Errno 2] No such file or directory: '/omd/sites/<sitename>/local/share/check_mk/notifications/telegram_plus_notify_listener'`

The problem is that the `telegram_plus_notify_listener` script uses windows-style line endings (CR LF) instead of unix ones (LF). This is not allowed for a shebang, causing this error:
```
-bash: /omd/sites/<sitename>/local/share/check_mk/notifications/telegram_plus_notify_listener: /bin/bash^M: bad interpreter: No such file or directory
```

After converting the line endings to unix, the script successfully runs.

**Comment by deexno** [comment]
Thank you, I have now found this out at the same time through the following forum entry: https://forum.checkmk.com/t/problem-with-the-creation-of-a-notification-script/37323/8

Thanks for your help, **I have tested it in my test environment and this problem should be solved now!**
