### ISSUE TITLE
Limit access admin menu

### ISSUE THREAD

**Issue by devilofhell87** [deexno/checkmk-telegram-plus#10]
Hi,

can you provide a method to limit the access to the admin menu?

We would like to hide this menu for some users.

**Comment by deexno** [comment]
This function was introduced with the new release v3.2.0. Please read the following instructions to whitelist users for this option:

https://github.com/deexno/checkmk-telegram-plus/tree/main?tab=readme-ov-file#activate-the-admin-settings-only-for-certain-users

All users of the bot will still see the option field/button but only whitelisted users can open the option. Users who have not been activated for this will receive the following message when they press the button: THE ADMIN SETTINGS ARE DEACTIVATED FOR YOU!

If the admin_user option is not configured / empty, all users can access it

**Comment by devilofhell87** [comment]
Hi,

we have set the option and restart the service, but all the users see the admin menu.

How can we debug this?

**Comment by deexno** [comment]
Yes, as I already told you in the previous answer:

> All users of the bot will still see the option field/button but only whitelisted users can open the option. Users who have not been activated for this will receive the following message when they press the button: THE ADMIN SETTINGS ARE DEACTIVATED FOR YOU!
