### ISSUE TITLE
/cancel not cancelling the entire conversation when using "reschedule check"

### ISSUE THREAD

**Issue by virus2500** [deexno/checkmk-telegram-plus#3]
Hi again :)

Cancel seems not to cancel the entire conversation.

Steps to reproduce:
1) hit reschedule check
2) select a hostgroup (and missclick on a group you don't want)
3) type /cancel
    bot replies with "Conversation cancelled X"
4) hit reschedule again
    bot replies (without letting you select a hostgroup etc)
```
Failed to lookup IPv4 address of 🔄 RESCHEDULE CHECK via DNS: [Errno -2] Name or service not known

RESCHEDULE CHECK WAS COMPLETED SUCCESSFULLY
```

**Comment by deexno** [comment]
Okay that was fast, but the problem should be solved now. I tested it on my environment and it works there.

To update, you can simply delete the old install script on the server (if you don't have it already) and then run the installation/update process again with all 3 parameters.

If the problem still exists, you can open this issue entry again.

**Comment by virus2500** [comment]
It's working nicely now :) 

You rock 👍
