### ISSUE TITLE
 Issue with checkmk Plugin on GitHub After Language Change

### ISSUE THREAD

**Issue by syberx** [deexno/checkmk-telegram-plus#9]
I've been using the Telegram plugin on checkmk without any issues for months. However, after I changed the language settings to German yesterday, the checkmk server started exhibiting high resource usage, with 100% CPU and RAM utilization, leading to significant performance degradation. Stopping the Telegram plugin seems to alleviate the issue, indicating a possible link between the plugin and the server's performance problems.

I have tried uninstalling and reinstalling the plugin, but the issue persists, and I haven't found any clear error messages to diagnose the problem. I even increased the RAM allocation to 5GB and the CPU allocation to 6 cores, considering it's running on a current i7 processor, but the issue still remains.

The log doesn't provide much useful information. Here's what I see when I run the telegram_bot.py script:

```
root@checkmk:~# su - $omd_site_name
OMD[monitoring]:~$ cd local/share/checkmk-telegram-plus
OMD[monitoring]:~/local/share/checkmk-telegram-plus$ python3 telegram_bot.py
Run time of job "message_all_users (trigger: date[2024-02-03 09:07:46 UTC], next run at: 2024-02-03 09:07:46 UTC)" was missed by 0:00:02.938143
Killed
OMD[monitoring]:~/local/share/checkmk-telegram-plus$
```

I'm looking for assistance in resolving this issue. The sudden increase in resource utilization seems to be correlated with the language change in the Telegram plugin, and I need help identifying the root cause and implementing a solution.

Edit:
I have change de to en in config.ini same ...

I see in my logs 1100000000000000000 errors all same:
2024-01-31 14:07:36,629:CRITICAL:notifcation_listener:[Errno 2] No such file or directory: '/omd/sites/monitoring/tmp/telegram_plus/notifications.queue'

edit2:
i have create a folder tmp/telegram_plus/notifications.queue now its working ... also with language de .. crazy. 

Please new cool Updates :) 

CLOSE

**Comment by syberx** [comment]
Close....

**Comment by deexno** [comment]
So I can't explain that what you did in the 2nd edit solved the problem, but okay. Then I'll close this issue after your statement "close".
